Repository google/ExoPlayer, pull requests merged in 2019-07, with the labels that each got.

#6119 Update TrackSelectionDialog.java
  demos/main/src/main/java/com/google/android/exoplayer2/demo/TrackSelectionDialog.java
Labels: cla: yes, should merge

#5732 #5731 Add license information to generated POM files
  build.gradle
  publish.gradle
Labels: cla: yes, should merge

#6150 r2.10.3
  RELEASENOTES.md
  build.gradle
  constants.gradle
  demos/main/src/main/java/com/google/android/exoplayer2/demo/TrackSelectionDialog.java
  extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java
  library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerLibraryInfo.java
  library/core/src/main/java/com/google/android/exoplayer2/SimpleExoPlayer.java
  library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java
  library/core/src/main/java/com/google/android/exoplayer2/audio/MediaCodecAudioRenderer.java
  library/core/src/main/java/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.java
  library/core/src/main/java/com/google/android/exoplayer2/drm/ExoMediaDrm.java
  library/core/src/main/java/com/google/android/exoplayer2/drm/FrameworkMediaDrm.java
  library/core/src/main/java/com/google/android/exoplayer2/extractor/flv/AudioTagPayloadReader.java
  library/core/src/main/java/com/google/android/exoplayer2/extractor/flv/FlvExtractor.java
  library/core/src/main/java/com/google/android/exoplayer2/extractor/flv/ScriptTagPayloadReader.java
  library/core/src/main/java/com/google/android/exoplayer2/extractor/flv/TagPayloadReader.java
  library/core/src/main/java/com/google/android/exoplayer2/extractor/flv/VideoTagPayloadReader.java
  library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecInfo.java
  library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java
  library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadHelper.java
  library/core/src/main/java/com/google/android/exoplayer2/scheduler/PlatformScheduler.java
  library/core/src/main/java/com/google/android/exoplayer2/source/ProgressiveMediaPeriod.java
  library/core/src/main/java/com/google/android/exoplayer2/text/cea/Cea608Decoder.java
  library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CacheDataSink.java
  library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CacheDataSinkFactory.java
  library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java
  library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/DashManifestParser.java
  library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/SegmentBase.java
  library/smoothstreaming/src/main/java/com/google/android/exoplayer2/source/smoothstreaming/manifest/SsManifestParser.java
  library/ui/build.gradle
  library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerView.java
  publish.gradle
  testutils/src/main/java/com/google/android/exoplayer2/testutil/DebugRenderersFactory.java
Labels: cla: yes

#6042 Add convenience constructors for notification channel descriptions
  library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadService.java
  library/core/src/main/java/com/google/android/exoplayer2/util/NotificationUtil.java
  library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java
Labels: cla: yes, pending comments

#6178 TextTrackScore in a same manner than AudioTrackScore
  library/core/src/main/java/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.java
Labels: cla: yes, should merge
